"""
Data Service for Dashboard.

Reads data from JSON files generated by the Strategy Lab.
Adheres to DOC-06/DOC-07 IPC architecture.
"""

import json
import logging
from pathlib import Path
from datetime import datetime, date, timezone
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

class DataService:
    """
    Service to read Strategy Lab state from disk.
    """
    
    def __init__(self, data_dir: str = "data"):
        self.data_dir = Path(data_dir)
        self.status_file = self.data_dir / "system_status.json"
        self.universe_file = self.data_dir / "active_universe.json"
        self.signals_file = self.data_dir / "signals_cache.json"
        self.paper_portfolio_file = self.data_dir / "paper_portfolios.json"
        self.costs_dir = self.data_dir / "costs"

    def get_system_status(self) -> Dict[str, Any]:
        """Get current system heartbeat and status."""
        if not self.status_file.exists():
            return {"is_running": False, "status": "Offline (No status file)"}
            
        try:
            with open(self.status_file, 'r') as f:
                data = json.load(f)
                
            # Check staleness (if > 2 min old, maybe froze/stopped)
            ts =  datetime.fromisoformat(data.get("timestamp", "")) if data.get("timestamp") else None
            is_stale = False
            if ts:
                # Naive check, assuming UTC
                delta = (datetime.now(timezone.utc) - ts).total_seconds()
                if delta > 120:
                    data["is_running"] = False # Override if stale
                    data["status_note"] = f"Stale ({int(delta)}s ago)"
                    
            return data
        except Exception as e:
            logger.error(f"Error reading status: {e}")
            return {"is_running": False, "error": str(e)}

    def get_active_universe(self) -> Dict[str, Any]:
        """Get currently active universe symbols."""
        if not self.universe_file.exists():
            return {"active_symbols": [], "status": "No universe data"}
            
        try:
            with open(self.universe_file, 'r') as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error reading universe: {e}")
            return {}

    def get_recent_signals(self) -> Dict[str, Any]:
        """Get most recent generated signals."""
        if not self.signals_file.exists():
            return {"signals": []}
            
        try:
            with open(self.signals_file, 'r') as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error reading signals: {e}")
            return {"signals": []}

    def get_paper_portfolio(self) -> Dict[str, Any]:
        """Get paper trading portfolio status."""
        if not self.paper_portfolio_file.exists():
            return {"portfolios": {}}
            
        try:
            with open(self.paper_portfolio_file, 'r') as f:
                return json.load(f)
        except Exception as e:
            logger.error(f"Error reading portfolio: {e}")
            return {"portfolios": {}}

    def get_todays_costs(self) -> Dict[str, Any]:
        """Get AI cost tracking for today."""
        today = date.today().isoformat()
        cost_file = self.costs_dir / f"{today}.json"
        
        if not cost_file.exists():
            return {"total_cost_usd": 0.0, "total_tokens": 0, "total_searches": 0}
            
        try:
            with open(cost_file, 'r') as f:
                data = json.load(f)
                return data.get("summary", {})
        except Exception as e:
            logger.error(f"Error reading costs: {e}")
            return {}

# Singleton
_data_service = None

def get_data_service() -> DataService:
    global _data_service
    if _data_service is None:
        _data_service = DataService()
    return _data_service
